services:
  - type: web
    name: cygo-studio-web-fronet
    env: node
    plan: free
    buildCommand: CI=false npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production