services:
  - type: web
    name: cygo-studio-web-fronet
    env: node
    buildCommand: npm install && CI=false npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000