services:
  - type: web
    name: cygo-studio-web-fronet
    env: node
    region: ohio
    plan: free
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000