services:
  - type: web
    name: cygo-studio-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    autoDeploy: true